In [2]:
!pip install google-api-python-client

Requirement already satisfied: google-api-python-client in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (2.191.0)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from google-api-python-client) (0.31.2)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from google-api-python-client) (2.48.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from google-api-python-client) (0.3.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from google-api-python-client) (2.30.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from google-api-python-client) (4.2.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.72.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (6.33.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.27.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.32.5)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (46.0.5)
Requirement already satisfied: rsa<5,>=3.1.4 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (4.9.1)
Requirement already satisfied: pyparsing<4,>=3.1 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2026.1.4)
Requirement already satisfied: pyasn1>=0.1.3 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from rsa<5,>=3.1.4->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.6.2)
Requirement already satisfied: cffi>=2.0.0 in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (2.0.0)
Requirement already satisfied: pycparser in /Library/anaconda3/envs/Python/lib/python3.13/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (3.0)

In [1]:
from apiclient.discovery import build

DEVELOPER_KEY = "YOUR_KEY"

In [2]:
def video_search(youtube, q='自動化', max_results=50):

    responce = youtube.search().list(
        q = q,
        part = "id,snippet",
        order = "viewCount",
        type = "video",
        maxResults = max_results
    ).execute()

    items_id =[]
    items = responce['items']
    for item in items:
        item_id ={}
        item_id['video_id'] = item['id']['videoId']
        item_id['channel_id'] = item['snippet']['channelId']
        items_id.append(item_id)
    items_id
    df_video = pd.DataFrame(items_id)

    return df_video

In [3]:
import pandas as pd

In [ ]:
DEVELOPER_KEY = "YOUR KEY"
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"

youtube = build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION, developerKey=DEVELOPER_KEY)

df_video = video_search(youtube, q='Python 自動化', max_results=50)

In [5]:
df_video[:3]

      video_id                channel_id
0  PXMJ6FS7llk  UC8butISFwT-Wl7EV0hUK0BQ
1  bsq2YY-XAEo  UC0xRMqPOyRNPTaL6BxhbCnQ
2  -5v7CuXm7Ns  UCGlgXjYVoHLD86TQQ799WIw

In [7]:
df_video

       video_id                channel_id
0   PXMJ6FS7llk  UC8butISFwT-Wl7EV0hUK0BQ
1   bsq2YY-XAEo  UC0xRMqPOyRNPTaL6BxhbCnQ
2   -5v7CuXm7Ns  UCGlgXjYVoHLD86TQQ799WIw
3   TCYdZvlFYcQ  UCXZEtLHFgnCd9a9rqL661xA
4   Gd-BAxi9Vzw  UCbxNKPuL7G3M_Zjt03d2IYA
5   KmqEyT7HznQ  UC0xRMqPOyRNPTaL6BxhbCnQ
6   iju6xKZacGQ  UCVmKVD1r-RwmagvXCLR_dcw
7   FDnd3rPnKpc  UCc1sntWEyGXMhH0fXI5mMiQ
8   CBM7jUyHKho  UC2hMbZ-uopbfOqVSGlZKwng
9   IR2D0rrF2ow  UCEPBebrT6yUxgj5ZM7rnjdw
10  hQC6wYhcHXc  UCfQk5qGOEO5cPPDFlQe2lFQ
11  4oMvkvxUoZk  UCs2wvikhEq4NzeEwDfQqzkw
12  mYX9AaJF2lw  UCrZOiJyMbXpZ8T5snCIJaLA
13  tcCS8SbEZyw  UC1uj19dZQXa17-SqNGpVNLw
14  VzY4Hr8slwQ  UCvYRp9VEH7qdB7p9SJpnUGw
15  ximjGyZ93YQ  UCrZOiJyMbXpZ8T5snCIJaLA
16  JP_ugJny9X4  UC5Kgc_HNzx4GJ-w4QMeeKiQ
17  HuJV9Vq6snQ  UCGlgXjYVoHLD86TQQ799WIw
18  1OIRwL4zmp0  UCk-AjDBOodw8P40f0y6EYeA
19  qxRt-cS7XzU  UCedPzKBFt6W61gtfKp5tdzA
20  yFU003t-cTg  UCR9aFwQQm7cDzrHMOPsAvaA
21  bU7-a7IcJsY  UCZXRMLFAzFeQf-Qm5QnLWyA
22  zmrbS98KXyo  UC0xRMqPOyRNPTaL6BxhbCnQ
23  NvKowH8PnaA  UCSWj8mqQCcrcBlXPi4ThRDQ
24  WfVWoxi-QuQ  UCsE6ekuO6NSqgQMf_DPL8wQ

In [26]:
df_video['channel_id']

0     UC8butISFwT-Wl7EV0hUK0BQ
1     UC0xRMqPOyRNPTaL6BxhbCnQ
2     UCGlgXjYVoHLD86TQQ799WIw
3     UC0xRMqPOyRNPTaL6BxhbCnQ
4     UCEPBebrT6yUxgj5ZM7rnjdw
5     UCGlgXjYVoHLD86TQQ799WIw
6     UCs2wvikhEq4NzeEwDfQqzkw
7     UCrZOiJyMbXpZ8T5snCIJaLA
8     UC1uj19dZQXa17-SqNGpVNLw
9     UCrZOiJyMbXpZ8T5snCIJaLA
10    UC5Kgc_HNzx4GJ-w4QMeeKiQ
11    UCGlgXjYVoHLD86TQQ799WIw
12    UCk-AjDBOodw8P40f0y6EYeA
13    UCZXRMLFAzFeQf-Qm5QnLWyA
14    UC0xRMqPOyRNPTaL6BxhbCnQ
15    UCGlgXjYVoHLD86TQQ799WIw
16    UC0xRMqPOyRNPTaL6BxhbCnQ
17    UC0xRMqPOyRNPTaL6BxhbCnQ
18    UCJtUOos_MwJa_Ewii-R3cJA
19    UCGlgXjYVoHLD86TQQ799WIw
20    UCafFexaRoRylOKdzGBU6Pgg
21    UC0xRMqPOyRNPTaL6BxhbCnQ
22    UC5Kgc_HNzx4GJ-w4QMeeKiQ
23    UCGFxqqRaM97VjM5ToRfkoFg
24    UC5Kgc_HNzx4GJ-w4QMeeKiQ
25    UCGlgXjYVoHLD86TQQ799WIw
26    UCGlgXjYVoHLD86TQQ799WIw
27    UCGlgXjYVoHLD86TQQ799WIw
28    UCGlgXjYVoHLD86TQQ799WIw
29    UCGlgXjYVoHLD86TQQ799WIw
30    UC0xRMqPOyRNPTaL6BxhbCnQ
31    UC4iUfGeYbYhAySUwCZge9Ig
32    UCGlgXjYVoHLD86TQQ799WIw
33    UCO4Cruq71rw9S9lPDjJVyDA
34    UCNste53_VRtP6MGUfitOYQA
35    UC5Kgc_HNzx4GJ-w4QMeeKiQ
36    UC0xRMqPOyRNPTaL6BxhbCnQ
37    UCYZcEq9CHvf9vhazCZ0MvfA
38    UC0xRMqPOyRNPTaL6BxhbCnQ
39    UCGlgXjYVoHLD86TQQ799WIw
40    UCGlgXjYVoHLD86TQQ799WIw
41    UCy5cpoeTKqZ2cDzWX8NB3Gg
42    UCmhnQZJ3-UsiKG4EQvWAiVg
43    UCYPkI8lgfiNXmGxCglZhOwA
44    UCLsnK4MPVaqiVx3DSEqbb1A
45    UC5Kgc_HNzx4GJ-w4QMeeKiQ
46    UC0J7Yk_O3g1-x-xD7xxAE8Q
47    UC3EHkGEPITQLuxDjLVxIz9g
48    UC5Kgc_HNzx4GJ-w4QMeeKiQ
49    UCaeuEZcPrQMdMvI6VMFHc5Q
Name: channel_id, dtype: str

In [8]:
channel_ids = df_video['channel_id'].unique().tolist()
channel_ids[:3]

['UC8butISFwT-Wl7EV0hUK0BQ',
 'UC0xRMqPOyRNPTaL6BxhbCnQ',
 'UCGlgXjYVoHLD86TQQ799WIw']

In [9]:
subscriber_list = youtube.channels().list(
    id = ','.join(channel_ids),
    part = "statistics",
    fields = 'items(id, statistics(subscriberCount))'
).execute()

In [27]:
subscriber_list['items'][:5]

[{'id': 'UCmhnQZJ3-UsiKG4EQvWAiVg',
  'statistics': {'subscriberCount': '11700'}},
 {'id': 'UCZXRMLFAzFeQf-Qm5QnLWyA', 'statistics': {'subscriberCount': '290'}},
 {'id': 'UCk-AjDBOodw8P40f0y6EYeA',
  'statistics': {'subscriberCount': '113000'}},
 {'id': 'UCrZOiJyMbXpZ8T5snCIJaLA',
  'statistics': {'subscriberCount': '228000'}},
 {'id': 'UC8butISFwT-Wl7EV0hUK0BQ',
  'statistics': {'subscriberCount': '11500000'}}]

In [10]:
subscribers = []
for item in subscriber_list['items']:
    subscriber = {}
    subscriber['channel_id'] = item['id']
    subscriber['subscriber_count'] = int(item['statistics']['subscriberCount'])
    subscribers.append(subscriber)

df_subscribers = pd.DataFrame(subscribers)

In [11]:
df_subscribers[:5]

                 channel_id  subscriber_count
0  UCsE6ekuO6NSqgQMf_DPL8wQ             24400
1  UCXZEtLHFgnCd9a9rqL661xA             13800
2  UC1uj19dZQXa17-SqNGpVNLw             60700
3  UC2hMbZ-uopbfOqVSGlZKwng              1530
4  UCEPBebrT6yUxgj5ZM7rnjdw            387000

In [12]:
df = pd.merge(left=df_video, right=df_subscribers, on='channel_id')
df.head(3)

      video_id                channel_id  subscriber_count
0  PXMJ6FS7llk  UC8butISFwT-Wl7EV0hUK0BQ          11500000
1  bsq2YY-XAEo  UC0xRMqPOyRNPTaL6BxhbCnQ            164000
2  -5v7CuXm7Ns  UCGlgXjYVoHLD86TQQ799WIw            193000

In [13]:
df_extracted = df[df['subscriber_count'] < 10000]
df_extracted[:3]

       video_id                channel_id  subscriber_count
8   CBM7jUyHKho  UC2hMbZ-uopbfOqVSGlZKwng              1530
19  qxRt-cS7XzU  UCedPzKBFt6W61gtfKp5tdzA               578
20  yFU003t-cTg  UCR9aFwQQm7cDzrHMOPsAvaA              5950

In [14]:
video_ids = df_extracted['video_id'].tolist()

In [15]:
videos_list = youtube.videos().list(
    id = ','.join(video_ids),
    part = 'snippet,statistics',
    fields = 'items(id, snippet(title), statistics(viewCount))'
).execute()

In [16]:
videos_list

{'items': [{'id': 'CBM7jUyHKho',
   'snippet': {'title': 'AI Technology Exposed: The Real Python Farming Process for Meat and Skin'},
   'statistics': {'viewCount': '530681'}},
  {'id': 'qxRt-cS7XzU',
   'snippet': {'title': 'How to Install Python 3.13.1 on Windows 11 (2025)'},
   'statistics': {'viewCount': '389165'}},
  {'id': 'yFU003t-cTg',
   'snippet': {'title': '50+ Best AI Tools for Productivity in 2025 (ChatGPT, Canva, Notion & More!)'},
   'statistics': {'viewCount': '521992'}},
  {'id': 'bU7-a7IcJsY',
   'snippet': {'title': '【ひろゆき】経理の業務、PythonでExcel効率化したい #ひろゆき #ひろゆき切り抜き'},
   'statistics': {'viewCount': '199734'}}]}

In [17]:
videos_list['items'][:3]

[{'id': 'CBM7jUyHKho',
  'snippet': {'title': 'AI Technology Exposed: The Real Python Farming Process for Meat and Skin'},
  'statistics': {'viewCount': '530681'}},
 {'id': 'qxRt-cS7XzU',
  'snippet': {'title': 'How to Install Python 3.13.1 on Windows 11 (2025)'},
  'statistics': {'viewCount': '389165'}},
 {'id': 'yFU003t-cTg',
  'snippet': {'title': '50+ Best AI Tools for Productivity in 2025 (ChatGPT, Canva, Notion & More!)'},
  'statistics': {'viewCount': '521992'}}]

In [18]:
videos_info = []

items = videos_list['items']
for item in items:
    video_info = {}
    video_info['video_id'] = item['id']
    video_info['title'] = item['snippet']['title']
    video_info['view_count'] = item['statistics']['viewCount']
    videos_info.append(video_info)
df_videos_info = pd.DataFrame(videos_info)

In [19]:
df_videos_info

      video_id                                              title view_count
0  CBM7jUyHKho  AI Technology Exposed: The Real Python Farming...     530681
1  qxRt-cS7XzU  How to Install Python 3.13.1 on Windows 11 (2025)     389165
2  yFU003t-cTg  50+ Best AI Tools for Productivity in 2025 (Ch...     521992
3  bU7-a7IcJsY     【ひろゆき】経理の業務、PythonでExcel効率化したい #ひろゆき #ひろゆき切り抜き     199734

In [20]:
df_extracted

       video_id                channel_id  subscriber_count
8   CBM7jUyHKho  UC2hMbZ-uopbfOqVSGlZKwng              1530
19  qxRt-cS7XzU  UCedPzKBFt6W61gtfKp5tdzA               578
20  yFU003t-cTg  UCR9aFwQQm7cDzrHMOPsAvaA              5950
21  bU7-a7IcJsY  UCZXRMLFAzFeQf-Qm5QnLWyA               290

In [21]:
results = pd.merge(left=df_extracted, right=df_videos_info, on='video_id')
results

,video_id,channel_id,subscriber_count,title,view_count
0,CBM7jUyHKho,UC2hMbZ-uopbfOqVSGlZKwng,1530,AI Technology Exposed: The Real Python Farming...,530681
1,qxRt-cS7XzU,UCedPzKBFt6W61gtfKp5tdzA,578,How to Install Python 3.13.1 on Windows 11 (2025),389165
2,yFU003t-cTg,UCR9aFwQQm7cDzrHMOPsAvaA,5950,50+ Best AI Tools for Productivity in 2025 (Ch...,521992
3,bU7-a7IcJsY,UCZXRMLFAzFeQf-Qm5QnLWyA,290,【ひろゆき】経理の業務、PythonでExcel効率化したい #ひろゆき #ひろゆき切り抜き,199734

In [22]:
results = results.loc[:,['video_id', 'title', 'view_count', 'subscriber_count', 'channel_id']]
results

,video_id,title,view_count,subscriber_count,channel_id
0,CBM7jUyHKho,AI Technology Exposed: The Real Python Farming...,530681,1530,UC2hMbZ-uopbfOqVSGlZKwng
1,qxRt-cS7XzU,How to Install Python 3.13.1 on Windows 11 (2025),389165,578,UCedPzKBFt6W61gtfKp5tdzA
2,yFU003t-cTg,50+ Best AI Tools for Productivity in 2025 (Ch...,521992,5950,UCR9aFwQQm7cDzrHMOPsAvaA
3,bU7-a7IcJsY,【ひろゆき】経理の業務、PythonでExcel効率化したい #ひろゆき #ひろゆき切り抜き,199734,290,UCZXRMLFAzFeQf-Qm5QnLWyA